samples:

  Repli-HiC_K562_WT_totalS:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/Repli-HiC_K562_WT_totalS.hic"
    genome: "hg19"
    norm: "VC_SQRT"
    res: "50000"
    exp: "replihic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/Repli-HiC_K562_WT_totalS.ice.mcool"
  
  DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped.hic"
    genome: "mm10"
    norm: "KR"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped.ice.mcool"

  GSE199059_CD69negDPWTR1R2R3R4_merged:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE199059_CD69negDPWTR1R2R3R4_merged.hic"
    genome: "mm9"
    norm: "KR"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GSE199059_CD69negDPWTR1R2R3R4_merged.ice.mcool"

  splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9.hic"
    genome: "mm9"
    norm: "KR"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9.ice.mcool"

  GM12878_insitu-hic_4DNFI1UEG1HD:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_insitu-hic_4DNFI1UEG1HD.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_insitu-hic_4DNFI1UEG1HD.ice.mcool"

  # GM12878_cohesin_SMC1_RAD21_pooled_chiadrop_Kim-2024_4DNFI9JN3S8M_hg38:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_cohesin-SMC1-RAD21-pooled_chiadrop_Kim-2024_4DNFI9JN3S8M_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  # GM12878_CTCF_chiadrop_Kim-2024_4DNFIERR7BI33_hg38:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_CTCF_chiadrop_Kim-2024_4DNFIERR7BI3_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38.ice.mcool"

  # GM12878_control_chiapet_Kim-2024_GSE158897_GM19239_hg38:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_control_chiapet_Kim-2024_GSE158897-GM19239_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  # GM12878_CTCF_chiapet_Kim-2024_4DNFIR5BPZ5L_hg38:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_CTCF_chiapet_Kim-2024_4DNFIR5BPZ5L_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38.ice.mcool"

  GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38.ice.mcool"

  HCT116_RAD21_auxin_0hr_hic_Rao-2017_4DNFIP71EWXC_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.ice.mcool"

  HCT116_RAD21_auxin_6hr_hic_Rao-2017_4DNFILIM6FDL_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.ice.mcool"

  zebrafish_embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/zebrafish-embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11.hic"
    genome: "danRer11"
    norm: "KR"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/zebrafish-embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11.ice.mcool"

  c_elegans_CA1200_L2_L3_JK07_JK08_control_auxin_1hr_hic_Kim-2023_GSE188849_ce10:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-CA1200-L2-L3-JK07-JK08_control-auxin-1hr_hic_Kim-2023_GSE188849_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "40000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-CA1200-L2-L3-JK07-JK08_control-auxin-1hr_hic_Kim-2023_GSE188849_ce10.ice.mcool"

  c_elegans_JK05_L3_SMC3_auxin_1hr_hic_Kim-2023_GSE237663_ce10:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK05-L3_SMC3-auxin-1hr_hic_Kim-2023_GSE237663_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "40000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK05-L3_SMC3-auxin-1hr_hic_Kim-2023_GSE237663_ce10.ice.mcool"

  c_elegans_JK06_L3_WAPL_auxin_1hr_hic_Kim-2023_GSE237663_ce10:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK06-L3_WAPL-auxin-1hr_hic_Kim-2023_GSE237663_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "40000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK06-L3_WAPL-auxin-1hr_hic_Kim-2023_GSE237663_ce10.ice.mcool"

  GM12878_intacthic_ENCFF318GOM:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_intacthic_ENCFF318GOM.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_intacthic_ENCFF785BPC.ice.mcool"

  HCT116_RAD21_auxin_6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF461RFV_hg38.ice.mcool"

  HCT116_RAD21_auxin_0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF109GNA_hg38.ice.mcool"

  K562_hic_Rao-2014_ENCFF616PUW_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/K562_hic_Rao-2014_ENCFF616PUW_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/K562_hic_Rao-2014_4DNFI2R1W3YW_hg38.ice.mcool"

  K562_intacthic_ENCODE-2023_ENCFF621AIY_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/K562_intacthic_ENCODE-2023_ENCFF621AIY_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/K562_intacthic_ENCODE-2023_ENCFF808MAG_hg38.ice.mcool"

  mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"

  mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "NONE" # KR failed, VC_SQRT failed, VC failed
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"

  mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"

  mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"

  # FAILED COMBINING CODE. RERUN ANALYSIS WITH THIS FILE
  # GSE130275_mESC_WT_combined_2.6B: 
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.hic"
  #   genome: "mm10"
  #   norm: "KR"
  #   res: "50000"
  #   exp: "hic" # technically micro-C
  #   mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.mcool"
