samples:
  
  Repli-HiC_K562_WT_totalS:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/Repli-HiC_K562_WT_totalS.hic"
    genome: "hg19"
    norm: "VC_SQRT"
    res: "50000"
    exp: "replihic"
  
  DP_thymocytes_WT:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped.hic"
    genome: "mm10"
    norm: "KR"
    res: "50000"
    exp: "hic"

  GSE199059_CD69negDPWTR1R2R3R4_merged:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE199059_CD69negDPWTR1R2R3R4_merged.hic"
    genome: "mm9"
    norm: "KR"
    res: "50000"
    exp: "hic"

  splenic_B_cell_WT_insitu:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9.hic"
    genome: "mm9"
    norm: "KR"
    res: "50000"
    exp: "hic"

  GM12878_insitu_hic_4DNFI1UEG1HD:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_insitu-hic_4DNFI1UEG1HD.hic"
    genome: "hg38"
    norm: "KR"
    res: "50000"
    exp: "hic"

  # GM12878_cohesin_SMC1_RAD21_pooled_chiadrop_Kim-2024_4DNFI9JN3S8M:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_cohesin-SMC1-RAD21-pooled_chiadrop_Kim-2024_4DNFI9JN3S8M_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  # GM12878_CTCF_chiadrop_Kim-2024_4DNFIERR7BI3:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_CTCF_chiadrop_Kim-2024_4DNFIERR7BI3_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "50000"
    exp: "hic"


  # GM12878_control_chiapet_Kim-2024_GSE158897_GM19239:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_control_chiapet_Kim-2024_GSE158897-GM19239_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  # GM12878_CTCF_chiapet_Kim-2024_4DNFIR5BPZ5L:
  #   file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_CTCF_chiapet_Kim-2024_4DNFIR5BPZ5L_hg38.hic"
  #   genome: "hg38"
  #   norm: "NONE"
  #   res: "50000"
  #   exp: "hic"

  GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "50000"
    exp: "hic"

  GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "50000"
    exp: "hic"

  HCT116_RAD21_auxin_0hr_hic_Rao-2017_4DNFIP71EWXC:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"

  HCT116_RAD21_auxin_6hr_hic_Rao-2017_4DNFILIM6FDL:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"

  zebrafish_embryo_sperm_hic_Wike-2021_4DNFI4P145EM:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/zebrafish-embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11.hic"
    genome: "danRer11"
    norm: "KR"
    res: "50000"
    exp: "hic"

  c_elegans_CA1200_L2_L3_JK07_JK08_control_auxin_1hr_hic_Kim-2023_GSE188849:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-CA1200-L2-L3-JK07-JK08_control-auxin-1hr_hic_Kim-2023_GSE188849_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "40000"
    exp: "hic"

  c_elegans_JK05_L3_SMC3_auxin_1hr_hic_Kim-2023_GSE237663:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK05-L3_SMC3-auxin-1hr_hic_Kim-2023_GSE237663_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "40000"
    exp: "hic"

  c_elegans_JK06_L3_WAPL_auxin_1hr_hic_Kim-2023_GSE237663:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK06-L3_WAPL-auxin-1hr_hic_Kim-2023_GSE237663_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "40000"
    exp: "hic"

  GM12878_intacthic_ENCFF318GOM:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_intacthic_ENCFF318GOM.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000"
    exp: "hic"

  HCT116_RAD21_auxin_6hr_intacthic_Guckelberger-2024_ENCFF317OIA:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"

  HCT116_RAD21_auxin_0hr_intacthic_Guckelberger-2024_ENCFF528XGK:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"

  K562_hic_Rao-2014_ENCFF616PUW:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/K562_hic_Rao-2014_ENCFF616PUW_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"

  K562_intacthic_ENCODE-2023_ENCFF621AIY:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/K562_intacthic_ENCODE-2023_ENCFF621AIY_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000"
    exp: "hic"
