samples:

  Repli-HiC_K562_WT_totalS:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/Repli-HiC_K562_WT_totalS.hic"
    genome: "hg19"
    norm: "VC_SQRT"
    res: "25000"
    exp: "replihic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/Repli-HiC_K562_WT_totalS.ice.mcool"
    win: "6000000"
    chroms: "all"

  K562_hic_Rao-2014_ENCFF616PUW_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/K562_hic_Rao-2014_ENCFF616PUW_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/K562_hic_Rao-2014_4DNFI2R1W3YW_hg38.ice.mcool"
    win: "6000000"
    chroms: "all"

  K562_intacthic_ENCODE-2023_ENCFF621AIY_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/K562_intacthic_ENCODE-2023_ENCFF621AIY_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/K562_intacthic_ENCODE-2023_ENCFF808MAG_hg38.ice.mcool"
    win: "6000000"
    chroms: "all"
  
  DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped.hic"
    genome: "mm10"
    norm: "KR"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/DP-thymocytes_WT_hic_Guo-2022_GSE199059_mm10-remapped.ice.mcool"
    win: "6000000"
    chroms: "all"

  GSE199059_CD69negDPWTR1R2R3R4_merged:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE199059_CD69negDPWTR1R2R3R4_merged.hic"
    genome: "mm9"
    norm: "KR"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GSE199059_CD69negDPWTR1R2R3R4_merged.ice.mcool"
    win: "6000000"
    chroms: "all"

  splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9.hic"
    genome: "mm9"
    norm: "KR"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/splenic-B-cell_WT_insitu-hic_Kieffer-Kwon-2018_GSE82144_mm9.ice.mcool"
    win: "6000000"
    chroms: "all"

  GM12878_microc_Wu-2025_GSE225201_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_microc_Wu-2025_GSE225201_hg38.hic"
    genome: "hg38"
    norm: "KR"
    res: "25000"
    exp: "hic"
    # mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_microc_Wu-2025_GSE225201_hg38.ice.mcool" # Not downloaded but possible
    win: "6000000"
    chroms: "all"

  GM12878_insitu-hic_4DNFI1UEG1HD:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_insitu-hic_4DNFI1UEG1HD.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_insitu-hic_4DNFI1UEG1HD.ice.mcool"
    win: "6000000"
    chroms: "all"

  GM12878_intacthic_ENCFF318GOM:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_intacthic_ENCFF318GOM.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_intacthic_ENCFF785BPC.ice.mcool"
    win: "6000000"
    chroms: "all"


  GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RAD21_chiapet_Kim-2024_4DNFIV9RG6YP_hg38.ice.mcool"
    win: "6000000"
    chroms: "all"

  GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiapet_Kim-2024_4DNFICWBQKM9_hg38.ice.mcool"
    win: "6000000"
    chroms: "all"

  GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38.hic"
    genome: "hg38"
    norm: "NONE"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GM12878_RNAPII_chiadrop_Kim-2024_4DNFI3ZH8UYR_hg38.ice.mcool"
    win: "6000000"
    chroms: "all"


  zebrafish-embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/zebrafish-embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11.hic"
    genome: "danRer11"
    norm: "KR"
    res: "25000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/zebrafish-embryo_sperm_hic_Wike-2021_4DNFI4P145EM_z11.ice.mcool"
    win: "6000000"
    chroms: "all"
    compartment: "False"
    angle_turbulence: "0.4"

  c-elegans-CA1200-L2-L3-JK07-JK08_control-auxin-1hr_hic_Kim-2023_GSE188849_ce10:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-CA1200-L2-L3-JK07-JK08_control-auxin-1hr_hic_Kim-2023_GSE188849_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "5000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-CA1200-L2-L3-JK07-JK08_control-auxin-1hr_hic_Kim-2023_GSE188849_ce10.ice.mcool"
    win: "800000"
    chroms: "all"
    compartment: "True"
    q_val: "0.2"

  c-elegans-JK05-L3_SMC3-auxin-1hr_hic_Kim-2023_GSE237663_ce10:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK05-L3_SMC3-auxin-1hr_hic_Kim-2023_GSE237663_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "5000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK05-L3_SMC3-auxin-1hr_hic_Kim-2023_GSE237663_ce10.ice.mcool"
    win: "800000"
    chroms: "all"
    compartment: "True"
    q_val: "0.2"


  c-elegans-JK06-L3_WAPL-auxin-1hr_hic_Kim-2023_GSE237663_ce10:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK06-L3_WAPL-auxin-1hr_hic_Kim-2023_GSE237663_ce10.hic"
    genome: "ce10"
    norm: "KR"
    res: "5000"
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/c-elegans-JK06-L3_WAPL-auxin-1hr_hic_Kim-2023_GSE237663_ce10.ice.mcool"
    win: "800000"
    chroms: "all"
    compartment: "True"
    q_val: "0.2"


  HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38_25kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "25000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF461RFV_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38_25kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "25000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF109GNA_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"


  HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38_25kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "25000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38_25kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "25000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"


  HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38_50kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF461RFV_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38_50kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "50000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF109GNA_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"


  HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38_50kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38_50kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "50000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38_10kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF317OIA_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "10000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_intacthic_Guckelberger-2024_ENCFF461RFV_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38_10kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF528XGK_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT" # KR failed
    res: "10000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_intacthic_Guckelberger-2024_ENCFF109GNA_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"


  HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38_10kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "10000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-0hr_hic_Rao-2017_4DNFIP71EWXC_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"

  HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38_10kb:
    file: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.hic"
    genome: "hg38"
    norm: "VC_SQRT"
    res: "10000" # 10 kb problematic
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/HCT116_RAD21-auxin-6hr_hic_Rao-2017_4DNFILIM6FDL_hg38.ice.mcool"
    win: "1200000"
    chroms: "all"




  mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_2nkb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "20000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_2nkb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "NONE" # KR failed, VC_SQRT failed, VC failed
    res: "20000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_2nkb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "20000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_2nkb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "20000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  GSE130275_mESC_WT_combined_2.6B_2nkb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.hic"
    genome: "mm10"
    norm: "KR"
    res: "25000" # 10 kb problematic
    exp: "hic" # technically micro-C
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.ice.mcool"
    win: "5000000"
    chroms: "all"


  mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_50kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "50000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_50kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "NONE" # KR failed, VC_SQRT failed, VC failed
    res: "50000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_50kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "50000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_50kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "50000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "5000000"
    chroms: "all"

  GSE130275_mESC_WT_combined_2.6B_50kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.hic"
    genome: "mm10"
    norm: "KR"
    res: "50000" # 10 kb problematic
    exp: "hic" # technically micro-C
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.ice.mcool"
    win: "5000000"
    chroms: "all" 




  mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_10kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "10000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_CTCF-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "2000000"
    chroms: "all"

  mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_10kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "NONE" # KR failed, VC_SQRT failed, VC failed
    res: "10000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_RAD21-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "2000000"
    chroms: "all"

  mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_10kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "10000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_YY1-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "2000000"
    chroms: "all"

  mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10_10kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.hic"
    genome: "mm10"
    norm: "VC_SQRT"
    res: "10000" # 10 kb problematic, 25 kb not present
    exp: "hic"
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/mESC_WAPL-auxin-3hr_microc_Hsieh-2022_GSE178982_mm10.mcool"
    win: "2000000"
    chroms: "all"

  GSE130275_mESC_WT_combined_2.6B_10kb: 
    file: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.hic"
    genome: "mm10"
    norm: "KR"
    res: "10000" # 10 kb problematic
    exp: "hic" # technically micro-C
    mcool: "/nfs/turbo/umms-minjilab/downloaded_data/GSE130275_mESC_WT_combined_2.6B.ice.mcool"
    win: "2000000"
    chroms: "all" 



  






  





